export const REVIEWS = [
  {
    name: "User 1",
    email: "user1@example.com",
    rating: "4",
    comment: "I love the product and how easy it is to use it!",
    date: new Date("2023-07-14T14:00:00"),
  },
  {
    name: "User 2",
    email: "user2@example.com",
    rating: "3",
    comment: "I love the product and how easy it is to use it!",
    date: new Date("2023-07-14T13:00:00"),
  },
  {
    name: "User 3",
    email: "user3@example.com",
    rating: "2",
    comment: "Great product! Highly recommended!",
    date: new Date("2023-07-12T14:00:00"),
  },

  {
    name: "User 5",
    email: "user5@example.com",
    rating: "4",
    comment: "I love the product and how easy it is to use it!",
    date: new Date("2023-07-13T14:00:00"),
  },
  {
    name: "User 6",
    email: "user6@example.com",
    rating: "3",
    comment: "Not satisfied with the product. Needs major improvements.",
    date: new Date("2023-07-11T12:00:00"),
  },
  {
    name: "User 7",
    email: "user7@example.com",
    rating: "2",
    comment: "I love the product and how easy it is to use it!",
    date: new Date("2023-07-11T11:00:00"),
  },
  {
    name: "User 8",
    email: "user8@example.com",
    rating: "4",
    comment: "I love the product and how easy it is to use it!",
    date: new Date("2023-06-11T12:00:00"),
  },
  {
    name: "User 9",
    email: "user9@example.com",
    rating: "5",
    comment: "Great product! Highly recommended!",
    date: new Date("2023-06-11T11:00:00"),
  },
  {
    name: "User 10",
    email: "user10@example.com",
    rating: "3",
    comment: "I love the product and how easy it is to use it!",
    date: new Date("2023-06-11T10:00:00"),
  },
  {
    name: "User 11",
    email: "user11@example.com",
    rating: "5",
    comment: "Not satisfied with the product. Needs major improvements.",
    date: new Date("2023-06-11T09:00:00"),
  },
  {
    name: "User 12",
    email: "user12@example.com",
    rating: "1",
    comment: "Great product! Highly recommended!",
    date: new Date("2023-06-11T08:00:00"),
  },
  {
    name: "User 13",
    email: "user13@example.com",
    rating: "5",
    comment: "Great product! Highly recommended!",
    date: new Date("2023-06-11T07:00:00"),
  },
  {
    name: "User 14",
    email: "user14@example.com",
    rating: "4",
    comment: "Good product, but could use some improvements.",
    date: new Date("2023-06-11T06:00:00"),
  },
  {
    name: "User 15",
    email: "user15@example.com",
    rating: "5",
    comment: "Good product, but could use some improvements.",
    date: new Date("2023-06-11T05:00:00"),
  },
]
